INSERT INTO notification_templates (event_type, channel, locale, subject, text_body, html_body)
VALUES
  ('tx.created', 'email', 'en',
   'Your transaction was created',
   'Hi {{name}}, your transaction {{txId}} has been created.',
   '<p>Hi {{name}}, your transaction {{txId}} has been created.</p>'),
  ('tx.created', 'sms', 'en',
   NULL,
   'Your transaction {{txId}} was created.',
   NULL),
  ('tx.created', 'push', 'en',
   NULL,
   'Transaction created: {{txId}}',
   NULL),
  ('tx.created', 'webhook', 'en',
   NULL,
   '{"event":"tx.created","txId":"{{txId}}"}',
   NULL),

  ('payment.captured', 'email', 'en',
   'Payment captured',
   'Hi {{name}}, we captured your payment of {{amount}} {{currency}}.',
   '<p>Hi {{name}}, we captured your payment of {{amount}} {{currency}}.</p>'),
  ('payment.captured', 'sms', 'en',
   NULL,
   'Payment captured: {{amount}} {{currency}}',
   NULL),
  ('payment.captured', 'push', 'en',
   NULL,
   'Payment captured: {{amount}} {{currency}}',
   NULL),
  ('payment.captured', 'webhook', 'en',
   NULL,
   '{"event":"payment.captured","txId":"{{txId}}","amount":"{{amount}}","currency":"{{currency}}"}',
   NULL),

  ('tx.signed', 'email', 'en',
   'Transaction signed',
   'Hi {{name}}, your transaction {{txId}} has been signed.',
   '<p>Hi {{name}}, your transaction {{txId}} has been signed.</p>'),
  ('tx.signed', 'sms', 'en',
   NULL,
   'Transaction signed: {{txId}}',
   NULL),
  ('tx.signed', 'push', 'en',
   NULL,
   'Transaction signed: {{txId}}',
   NULL),
  ('tx.signed', 'webhook', 'en',
   NULL,
   '{"event":"tx.signed","txId":"{{txId}}"}',
   NULL),

  ('tx.confirmed', 'email', 'en',
   'Transaction confirmed',
   'Hi {{name}}, your transaction {{txId}} is confirmed on-chain.',
   '<p>Hi {{name}}, your transaction {{txId}} is confirmed on-chain.</p>'),
  ('tx.confirmed', 'sms', 'en',
   NULL,
   'Confirmed: {{txId}}',
   NULL),
  ('tx.confirmed', 'push', 'en',
   NULL,
   'Transaction confirmed: {{txId}}',
   NULL),
  ('tx.confirmed', 'webhook', 'en',
   NULL,
   '{"event":"tx.confirmed","txId":"{{txId}}"}',
   NULL),

  ('tx.failed', 'email', 'en',
   'Transaction failed',
   'Hi {{name}}, your transaction {{txId}} failed: {{reason}}.',
   '<p>Hi {{name}}, your transaction {{txId}} failed: {{reason}}.</p>'),
  ('tx.failed', 'sms', 'en',
   NULL,
   'Transaction failed: {{txId}}',
   NULL),
  ('tx.failed', 'push', 'en',
   NULL,
   'Transaction failed: {{txId}}',
   NULL),
  ('tx.failed', 'webhook', 'en',
   NULL,
   '{"event":"tx.failed","txId":"{{txId}}","reason":"{{reason}}"}',
   NULL),

  ('tx.refunded', 'email', 'en',
   'Refund processed',
   'Hi {{name}}, your transaction {{txId}} was refunded: {{amount}} {{currency}}.',
   '<p>Hi {{name}}, your transaction {{txId}} was refunded: {{amount}} {{currency}}.</p>'),
  ('tx.refunded', 'sms', 'en',
   NULL,
   'Refunded: {{amount}} {{currency}} for {{txId}}',
   NULL),
  ('tx.refunded', 'push', 'en',
   NULL,
   'Refund processed: {{txId}}',
   NULL),
  ('tx.refunded', 'webhook', 'en',
   NULL,
   '{"event":"tx.refunded","txId":"{{txId}}","amount":"{{amount}}","currency":"{{currency}}"}',
   NULL)
ON CONFLICT (event_type, channel, locale) DO NOTHING;