-- Stage 1: seed the six lifecycle templates (event types x channels x en locale)
-- Templates are also inserted for chain.confirmed (event source alias).
-- NOTE: Uses UPSERT so re-running the migration is idempotent.

INSERT INTO notification_templates (event_type, channel, locale, subject, text_body, html_body, short_body)
VALUES
  ('tx.created','email','en',
   'Transaction {{tx_id}} created',
   'Hi {{user_name}}, your transaction {{tx_id}} for {{amount}} {{currency}} has been created and is awaiting payment.',
   '<p>Hi {{user_name}},</p><p>Your transaction <strong>{{tx_id}}</strong> for {{amount}} {{currency}} has been created and is awaiting payment.</p>',
   'Tx {{tx_id}} created: {{amount}} {{currency}}.'),
  ('tx.created','sms','en','','Tx {{tx_id}} created: {{amount}} {{currency}}.','','Tx {{tx_id}} created: {{amount}} {{currency}}.'),
  ('tx.created','push','en','','Tx {{tx_id}} created: {{amount}} {{currency}}.','','Tx {{tx_id}} created: {{amount}} {{currency}}.'),
  ('payment.captured','email','en',
   'Payment captured for {{tx_id}}',
   'Hi {{user_name}}, we captured your payment of {{amount}} {{currency}} for transaction {{tx_id}}.',
   '<p>Hi {{user_name}},</p><p>We captured your payment of <strong>{{amount}} {{currency}}</strong> for transaction {{tx_id}}.</p>',
   'Payment captured for tx {{tx_id}}: {{amount}} {{currency}}.'),
  ('payment.captured','sms','en','','Payment captured for tx {{tx_id}}: {{amount}} {{currency}}.','','Payment captured for tx {{tx_id}}: {{amount}} {{currency}}.'),
  ('payment.captured','push','en','','Payment captured for tx {{tx_id}}: {{amount}} {{currency}}.','','Payment captured for tx {{tx_id}}: {{amount}} {{currency}}.'),
  ('tx.signed','email','en',
   'Transaction {{tx_id}} signed',
   'Hi {{user_name}}, transaction {{tx_id}} was signed and is now queued for broadcast.',
   '<p>Hi {{user_name}},</p><p>Transaction {{tx_id}} was signed and is now queued for broadcast.</p>',
   'Tx {{tx_id}} signed and queued.'),
  ('tx.signed','sms','en','','Tx {{tx_id}} signed and queued.','','Tx {{tx_id}} signed and queued.'),
  ('tx.signed','push','en','','Tx {{tx_id}} signed and queued.','','Tx {{tx_id}} signed and queued.'),
  ('tx.confirmed','email','en',
   'Transaction {{tx_id}} confirmed',
   'Hi {{user_name}}, transaction {{tx_id}} is confirmed on {{chain}} with {{confirmations}} confirmations.',
   '<p>Hi {{user_name}},</p><p>Transaction {{tx_id}} is confirmed on {{chain}} with {{confirmations}} confirmations.</p>',
   'Tx {{tx_id}} confirmed on {{chain}} ({{confirmations}} conf).'),
  ('tx.confirmed','sms','en','','Tx {{tx_id}} confirmed on {{chain}} ({{confirmations}} conf).','','Tx {{tx_id}} confirmed on {{chain}} ({{confirmations}} conf).'),
  ('tx.confirmed','push','en','','Tx {{tx_id}} confirmed on {{chain}} ({{confirmations}} conf).','','Tx {{tx_id}} confirmed on {{chain}} ({{confirmations}} conf).'),
  ('tx.failed','email','en',
   'Transaction {{tx_id}} failed',
   'Hi {{user_name}}, transaction {{tx_id}} failed. Reason: {{reason}}.',
   '<p>Hi {{user_name}},</p><p>Transaction {{tx_id}} failed. Reason: {{reason}}.</p>',
   'Tx {{tx_id}} failed: {{reason}}.'),
  ('tx.failed','sms','en','','Tx {{tx_id}} failed: {{reason}}.','','Tx {{tx_id}} failed: {{reason}}.'),
  ('tx.failed','push','en','','Tx {{tx_id}} failed: {{reason}}.','','Tx {{tx_id}} failed: {{reason}}.'),
  ('tx.refunded','email','en',
   'Refund issued for {{tx_id}}',
   'Hi {{user_name}}, a refund of {{amount}} {{currency}} for transaction {{tx_id}} has been issued.',
   '<p>Hi {{user_name}},</p><p>A refund of <strong>{{amount}} {{currency}}</strong> for transaction {{tx_id}} has been issued.</p>',
   'Refund {{amount}} {{currency}} issued for tx {{tx_id}}.'),
  ('tx.refunded','sms','en','','Refund {{amount}} {{currency}} issued for tx {{tx_id}}.','','Refund {{amount}} {{currency}} issued for tx {{tx_id}}.'),
  ('tx.refunded','push','en','','Refund {{amount}} {{currency}} issued for tx {{tx_id}}.','','Refund {{amount}} {{currency}} issued for tx {{tx_id}}.'),
  ('chain.confirmed','email','en',
   'Chain confirmation for {{tx_id}}',
   'Hi {{user_name}}, transaction {{tx_id}} reached chain finality on {{chain}}.',
   '<p>Hi {{user_name}},</p><p>Transaction {{tx_id}} reached chain finality on {{chain}}.</p>',
   'Tx {{tx_id}} chain-confirmed on {{chain}}.'),
  ('chain.confirmed','sms','en','','Tx {{tx_id}} chain-confirmed on {{chain}}.','','Tx {{tx_id}} chain-confirmed on {{chain}}.'),
  ('chain.confirmed','push','en','','Tx {{tx_id}} chain-confirmed on {{chain}}.','','Tx {{tx_id}} chain-confirmed on {{chain}}.')
ON CONFLICT (event_type, channel, locale) DO UPDATE
SET subject = EXCLUDED.subject,
    text_body = EXCLUDED.text_body,
    html_body = EXCLUDED.html_body,
    short_body = EXCLUDED.short_body,
    updated_at = now();